# Generated by Django 5.2.5 on 2025-09-06 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_created_at_task_created_by_task_updated_at_and_more'),
        ('tasks', '0003_task_is_active'),
    ]

    operations = [
    ]
